//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWNCoder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Überschrift")]
        public string title {
            get {
                return ((string)(this["title"]));
            }
            set {
                this["title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Button 1")]
        public string button1 {
            get {
                return ((string)(this["button1"]));
            }
            set {
                this["button1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Button 2")]
        public string button2 {
            get {
                return ((string)(this["button2"]));
            }
            set {
                this["button2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}
{\colortbl ;\red0\green255\blue0;\red0\green255\blue255;\red0\green128\blue255;\red255\green0\blue0;\red255\green202\blue202;\red0\green0\blue0;}
\viewkind4\uc1\pard\tx435\tx870\tx1290\tx1725\tx2160\tx2595\tx3015\tx3450\tx3885\tx4320\tx4740\tx5175\tx5610\tx6045\tx6465\tx6900\tx7335\tx7770\tx8190\tx8625\tx9060\tx9495\tx9915\tx10350\tx10785\tx11220\tx11640\tx12075\tx12510\tx12945\tx13365\tx13800\cf1\f0\fs18 Bitte\cf2  \cf3 einen\cf2  \cf4 Text\cf2  \cf5 eingeben\cf2 .\par
\par
\cf6 Copyright: RealGamer & Bubelbub =)\par
\par
0.1.3 mit Farb-Support!\par
0.1.3.1 mit Degenerierungsfunktion, \'dcberschrift Wechselbar, Button 1&2 Wechselbar. (Speichert alles!)\cf1\par
}")]
        public string lastcode {
            get {
                return ((string)(this["lastcode"]));
            }
            set {
                this["lastcode"] = value;
            }
        }
    }
}
